#inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - bin/**/*
    - ext/**/*
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Style/ModuleFunction:
#   Enabled: false

# Style/MultilineMethodCallIndentation:
#   EnforcedStyle: indented

# Style/SignalException:
#   EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes
