language: ruby
rvm:
  - jruby-19mode
  - jruby-head
  - 2.2
  - 2.3.1
jdk:
  - oraclejdk8
  - openjdk7
  - oraclejdk7
matrix:
  exclude:
    - rvm: 2.2
      jdk: oraclejdk7
    - rvm: 2.2
      jdk: openjdk8
    - rvm: 2.2
      jdk: oraclejdk8
    - rvm: 2.3.1
      jdk: openjdk7
    - rvm: 2.3.1
      jdk: oraclejdk7
    - rvm: 2.3.1
      jdk: oraclejdk8
    - rvm: jruby-19mode
      jdk: openjdk8
    - rvm: jruby-19mode
      jdk: oraclejdk8
# env:
  # global:
  #    - JRUBY_OPTS="-J-Xms256m -J-Xmx512m"
  #    - LDFLAGS="$LDFLAGS -z execstack"

script: 'bundle exec rake'

before_install:
  - gem install bundler

cache:
  - apt
  - bundler